name: Build and Deploy Java App
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build JAR Artifact and Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set Up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
      
    - name: Maven Build JAR Artifact 
      run: mvn -f app/pom.xml -B clean package

    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: app
        push: true
        tags: ewertonrdr/app:${{ github.sha }}, ewertonrdr/app:latest

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd  infra
          terraform init

      - name: Terraform Validate
        run: |
          cd  infra
          terraform validate

      - name: Terraform Plan
        run: |
          cd  infra
          terraform plan

        continue-on-error: true

      - name: Terraform Apply
        run: |
          cd  infra
          terraform apply -auto-approve -no-color

  kubernetes:
    name: EKS Auth And Helm Deploy
    runs-on: ubuntu-latest
    needs:
      - build
      - terraform

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Kube Config Data
      uses: azure/setup-kubectl@v1
      with:
        eks-region: us-east-1
        eks-cluster-name: app-eks-cluster
      env:
       KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Get Docker Image Version
      id: docker_image_version
      run: echo "::set-output name=docker_version::$(echo ${{ github.sha }} | cut -c1-7)"

    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest'

    - name: Update Chart.yaml
      run: |
        sed -i "s/^version:.*/version: $VERSION/" helm/Chart.yaml
      env:
        VERSION: ${{ github.run_number }}

    - name: Deploy with Helm
      run: |
        cd helm
        helm upgrade --install app

#    - name: Create Helm Release
#      run: helm upgrade --install app --set image.tag=${{ steps.docker_image_version.outputs.docker_version }} ewertonrdr/app --version 1.0.0
