name: Build and Deploy Java App
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test JAR Artifact 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set Up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
      
    - name: Maven Build JAR Artifact 
      run: mvn -f app/pom.xml -B clean package

  docker:
    name: Build Image and Upload to ECR
    runs-on: ubuntu-latest
    needs: 
      - build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

    - name: Create ECR Repo
      run: |
        set +e
        aws ecr describe-repositories --repository-names "${{ github.event.repository.name }}" > /dev/null 2>&1
        if [ $? -eq 0 ]; then
          echo "O repositório já existe."
        else
          aws ecr create-repository --repository-name "${{ github.event.repository.name }}"
        fi

    - name: Build and Push to ECR
      uses: docker/build-push-action@v5
      with:
        context: app
        push: true
        tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ github.event.repository.name }}:${{ github.sha }}, ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ github.event.repository.name }}:latest

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    needs:
      - build
      - docker

    steps:
      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd  infra
          terraform init

      - name: Terraform Validate
        run: |
          cd  infra
          terraform validate

      - name: Terraform Plan
        run: |
          cd  infra
          terraform plan

        continue-on-error: true

      - name: Check Destroy flag 
        id: check_destroy
        run: |
          cd infra
          content=$(jq -r .destroy cleaning.json)
          if [[ $content == "true" ]]; then
            echo "::set-output name=destroy::true"
          else
            echo "::set-output name=destroy::false"
          fi

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && steps.check_destroy.outputs.destroy == 'false'
        run: |
          cd  infra
          terraform apply -auto-approve -no-color

      - name: Terraform Destroy
        if: steps.check_destroy.outputs.destroy == 'true'
        run: terraform destroy -auto-approve

  kubernetes:
    name: EKS Auth And Helm Deploy
    runs-on: ubuntu-latest
    needs:
      - build
      - docker
      - terraform

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Kube Config Data
      uses: azure/setup-kubectl@v1
      env:
       KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Get Docker Image Version
      id: docker_image_version
      run: echo "::set-output name=docker_version::$(echo ${{ github.sha }} | cut -c1-7)"

    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest'

    - name: Update Chart.yaml
      run: |
        sed -i "s/^version:.*/version: $VERSION/" helm/Chart.yaml
      env:
        VERSION: ${{ github.run_number }}

    - name: Deploy with Helm
      run: |
        cd helm
        helm upgrade --install app --set image.tag=${{ steps.docker_image_version.outputs.docker_version }} ${{ github.event.repository.name }}