name: Build and Deploy Java App
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Java App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set Up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
      
    - name: Maven build JAR artifact 
      run: mvn -f app/pom.xml -B clean package

#    - name: Move Jar artifact to /app dir
#      run: mv app/target/*.jar app/app.jar

  docker:
     name: Build Docker Image
     runs-on: ubuntu-latest
     needs: build

     steps: 
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:app"
          push: true
          tags: ewertonrdr/app:${{ github.sha }}

  aws-credentials:
    runs-on: ubuntu-latest
    needs: 
      - build
      - docker

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

  terraform:
    runs-on: ubuntu-latest
    needs: 
      - build
      - docker
      - aws-credentials

    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: |
        cd /infra
        terraform init

    - name: Terraform Validate
      run: |
        cd /infra
        terraform validate -no-color

    - name: Terraform Plan
      run: |
        cd /infra
        terraform plan -no-color

      continue-on-error: true

    - name: Check Destroy flag 
      id: check_destroy
      run: |
        content=$(jq -r .destroy cleaning.json)
        if [[ $content == "true" ]]; then
          echo "::set-output name=destroy::true"
        else
          echo "::set-output name=destroy::false"
        fi

    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main' && steps.check_destroy.outputs.destroy == 'false'
      run: |
        cd infra
        terraform apply -auto-approve -no-color

    - name: Terraform Destroy
      id: destroy
      if: steps.check_destroy.outputs.destroy == 'true'
      run: |
        cd infra
        terraform destroy -auto-approve
