name: Build and deploy Java App
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set Up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
      
    - name: Maven build JAR artifact 
      run: mvn -f app/pom.xml -B clean package

    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build Image
      run: docker build -t ewertonrdr/app:${{ github.sha }}

    - name: Push Image
      run: docker push ewertonrdr/app:${{ github.sha }}

  aws-credentials:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
      
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init ./infra

    - name: Terraform Validate
      run: terraform validate -no-color ./infra


    - name: Terraform Plan
      run: terraform plan -no-color ./infra

      continue-on-error: true

    - name: Check Destroy flag 
      id: check_destroy
      run: |
        content=$(jq -r .destroy cleaning.json)
        if [[ $content == "true" ]]; then
          echo "::set-output name=destroy::true"
        else
          echo "::set-output name=destroy::false"
        fi

    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main' && steps.check_destroy.outputs.destroy == 'false'
      run: terraform apply -auto-approve -no-color ./infra


    - name: Terraform Destroy
      id: destroy
      if: steps.check_destroy.outputs.destroy == 'true'
      run: terraform destroy -auto-approve ./infra

